// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY8BrohHyQb3uQirZNvSv7m05Woq-mf3k',
    appId: '1:583267136931:web:b834c71f07110bc6d45616',
    messagingSenderId: '583267136931',
    projectId: 'gymhealthy-app',
    authDomain: 'gymhealthy-app.firebaseapp.com',
    storageBucket: 'gymhealthy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB49ztIb9VyHJX1CNnBBqSaBzH4RVjiHuE',
    appId: '1:583267136931:android:663daedcd4a04defd45616',
    messagingSenderId: '583267136931',
    projectId: 'gymhealthy-app',
    storageBucket: 'gymhealthy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvpoc8eoUrwjRA-pgpELLzoNuY5NVpeTw',
    appId: '1:583267136931:ios:0cee2960547eb42ad45616',
    messagingSenderId: '583267136931',
    projectId: 'gymhealthy-app',
    storageBucket: 'gymhealthy-app.firebasestorage.app',
    iosBundleId: 'com.example.aiGymhealthyApp',
  );
}
